version: '3.7'

services:
  php:
    image: mkphp:1.0
    volumes:
      - ./data/www/:/var/www/html/:cached
    ports:
      - 80:80
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: security
      MYSQL_USER: security
      MYSQL_PASSWORD: security
    ports:
      - "3307:3306"
    volumes:
      - ./data/mysql/:/var/lib/mysql