version: '3.7'

services:
  php:
    image: mkphp:1.0
    volumes:
      - ./data/www/:/var/www/html/:cached
  webserver:
    image: 'httpd:latest'
    depends_on:
      - php
    volumes:
      - ./data/www/:/var/www/html/:cached
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
    ports:
      - 80:80

  db:
    image: 'mysql:8.0'
    volumes:
      - ./data/mysql/:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
    ports:
      - '3306:3306'

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin:latest'
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root